<%@ Page Title="Social Media Toolkit" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="SocialMediaToolkit.aspx.cs" Inherits="NPO_SocialMediaToolkit" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Main_Content" Runat="Server">
    <h1>Using Social Media and Coupons4Giving</h1>
    <p>It’s the constant struggle as a <strong>Not For Profit</strong>. What is the best way to reach our supporters, not deluge them with requests, while maximizing the giving opportunity. And you have probably tried it all- <strong>mail campaigns</strong>, <strong>bingos and casinos</strong>, <strong>door to door</strong>, and even <strong>email campaigns</strong>.</p>
    
    <blockquote >Don’t stop doing those things.</blockquote> 
 
    <p>Its known as PUSH marketing, where you push requests and giving opportunities out to your client list. It’s probably worked in the past and in fact your supporters probably expect the annual cookie drive or the quarterly newsletter.  What Coupons4Giving does is provide you a <strong>SOCIAL ENGAGEMENT</strong> platform, allowing your supporters to support you more effectively, without all the hard work of door to door or late night casino closings.</p>
        
    <h2>Things to Know About Social Engagement</h2>
    <p>Right now the average Facebook user has over 300 friends. If you have 40 students in your not for profit ballet school, that means you can directly reach 1200 potential donors with a simple “support us with a coupon” post. Those 1200 know 300 more people and,well, you know the simple rules about social media already. But what’s important is that unlike email there isn’t a junk filter catching those messages, and two other important things are happening. Those 40 students are CHOOSING to post and the 1200 are CHOOSING to either share the post or buy a coupon. In the world of social engagement, you hope they do both.</p>
        
    <h2>Getting Ready</h2>
    <p>While clicking buttons and sharing posts is instantaneous, <strong>being an effective online marketer does not happen overnight</strong>. Your supporters will “like” your Facebook page, but you have to have one first. And they will follow you on Twitter if they feel you have something relevant and interesting to say. This should be the easy part for you the Not-for-Profit. A lot of your online support will probably start with either your donors or those users most affected by your Mission and goals. They are already looking to you to be the visionary, thought leader, and tireless worker that keeps the whole thing moving forward- that is why they support you with dollars in the first place.</p>
    
    <blockquote>So we believe our job at C4G is more than helping you sell coupons. We believe our job is also about making your online presence better.</blockquote>

    <h2>Here are some simple tips we propose to get you started.</h2>

    <ol>
        <li><img src="../images/c4g_home_npos_step3.png" class="right" /><strong>Get an Online Presence if you don’t have one</strong>. Sign up for <a href="https://www.facebook.com/" target="_blank">Facebook</a>, <a href="https://plus.google.com/" target="_blank">Google+</a>, <a href="http://www.twitter.com" target="_blank">Twitter</a>, and <a href="https://www.pinterest.com/" target="_blank">Pinterest</a> if you haven’t already. You can try <a href="http://www.linkedin.com/" target="_blank">LinkedIn</a> as well, but feel free to leave that network to the moms and dads who already have a corporate presence, or to larger regional and National NFP’s. We can show you some great examples of Not For Profits and their Social Media work if you need that help.</li>
        <li><strong>Sign up for Coupons4Giving</strong>. We will give you our online handbook and help you get started. And it becomes a first announcement to start driving traffic.</li>
        <li><strong>Take a few weeks to get your traffic up</strong>. Try to encourage your users, donors, and supporters to follow you on your social media sites. Others will follow suite very quickly once the word gets out. In fact following from #2 you might want to announce an exciting fundraiser is coming to your social media sites, so sign up now.</li>
        <li><strong>Show your major benefactors some love</strong>: Social media sites are a great way to say thanks. Post a thank you on facebook for that bank or law firm that has carried you for a long time. Make the social media sites and the recognition part of the donor package, and definitely, set up links to your donors online presence. Social media is about sharing- so share lots!! The more your sites are visible the more followers you get. So don’t forget to link to the national and regional associations you are a part of.</li>
        <li><strong>Do what you do best</strong>: You are the thought leader, the driver and the most passionate individual for your cause, so lead us. Share. Share articles we should be reading. Share schedules of when our kids should be at practice. Share important calendar dates. Make your online presence a “go to” destination  for your users and donors.</li>
        <li><img src="../images/c4g_tips_merchant_step4.png" class="right" /><strong><a href="~/NPO/Partners/Add.aspx" runat="server">Engage local merchants:</a></strong> We have a great list of international, national, and local merchants already, but there are probably three or four that you could add to work on your campaign specifically. A family that owns a bike shop whose son is in your organization. The cookie shop that has supported your blood drive in the past, or “that place” everybody already goes to in the community.<br /><br />In the past these merchants have probably felt the pressure of giving without a return. Coupons4Giving is set up so the merchants win too, so sign up that merchant whose time it is for your organization to “give back” to. <strong>Coupon4Giving is set up in a way that the merchant doesn’t lose money for helping out</strong>.</li>
        <li><strong><a runat="server" href="~/NPO/Campaigns/New.aspx">Start a Campaign!</a></strong> If 1-5 is part of your management mantra already, lets get going now! But if this is new to you, read our handbook, take some time to build up that online presence, and in a few weeks, lets work together to give your supporters an online purpose.</li>
    </ol>
    
    <p>The handbook will give you ideas on how to improve your Facebook traffic, examples of Not For Profits that use social media well, and other Not For Profit tools. Feel free to request it if you feel it will help. We look forward to being part of your online success and fundraising!</p>
</asp:Content>