//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalizedScriptResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NewOfferResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewOfferResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalizedScriptResources.NewOfferResources", typeof(NewOfferResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute limit of coupons to sell needs to be less than 10, 000..
        /// </summary>
        internal static string CouponLimitGT9999 {
            get {
                return ResourceManager.GetString("CouponLimitGT9999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute limit of coupons to sell must be greater than or equal to the limit per customer..
        /// </summary>
        internal static string CouponLimitLessThanCustomerLimit {
            get {
                return ResourceManager.GetString("CouponLimitLessThanCustomerLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your absolute coupon limit needs to be greater than 0..
        /// </summary>
        internal static string CouponLimitLT0 {
            get {
                return ResourceManager.GetString("CouponLimitLT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your absolute coupon limit needs to be a number. For example, 2500..
        /// </summary>
        internal static string CouponLimitNAN {
            get {
                return ResourceManager.GetString("CouponLimitNAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer description contains invalid characters. Please ensure it does not contain any of the following: &amp;lt;, &amp;gt;, {, }, or ;..
        /// </summary>
        internal static string DescriptionInvalidCharacters {
            get {
                return ResourceManager.GetString("DescriptionInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer description needs to be more than one word..
        /// </summary>
        internal static string DescriptionOneWord {
            get {
                return ResourceManager.GetString("DescriptionOneWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer description is too long. Offer descriptions need to be less than 200 characters long..
        /// </summary>
        internal static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer description is too short. Offers descriptions need to be at least 10 characters long..
        /// </summary>
        internal static string DescriptionTooShort {
            get {
                return ResourceManager.GetString("DescriptionTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date of your offer needs to be later than today&amp;apos;s date..
        /// </summary>
        internal static string EndDateBeforeToday {
            get {
                return ResourceManager.GetString("EndDateBeforeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date of your offer needs to be after its start date..
        /// </summary>
        internal static string EndDateEarlierThanStartDate {
            get {
                return ResourceManager.GetString("EndDateEarlierThanStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some errors with your form submission. Please review the following errors and try again..
        /// </summary>
        internal static string FormErrors {
            get {
                return ResourceManager.GetString("FormErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The gift value of your offer must be less than than its retail value..
        /// </summary>
        internal static string GiftValueGreaterThanRetailValue {
            get {
                return ResourceManager.GetString("GiftValueGreaterThanRetailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gift value needs to be greater than $1.00..
        /// </summary>
        internal static string GiftValueLT1 {
            get {
                return ResourceManager.GetString("GiftValueLT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gift value needs to be a number. For example, 25.00..
        /// </summary>
        internal static string GiftValueNAN {
            get {
                return ResourceManager.GetString("GiftValueNAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image you uploaded appears to be too large. We require images to be x pixels wide by y pixels high in order to display properly. Please select another image..
        /// </summary>
        internal static string ImageSizeInvalid {
            get {
                return ResourceManager.GetString("ImageSizeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you uploaded is an incorrect file type. Supported types include: GIF, JPEG, Progressive JPEG, PNG, and SVG. Please select another file..
        /// </summary>
        internal static string ImageTypeInvalid {
            get {
                return ResourceManager.GetString("ImageTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter an absolute limit for your offer. This is how many coupons you wish to sell overall..
        /// </summary>
        internal static string NullAbsoluteCouponLimit {
            get {
                return ResourceManager.GetString("NullAbsoluteCouponLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a description for your offer..
        /// </summary>
        internal static string NullDescription {
            get {
                return ResourceManager.GetString("NullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a gift value for your offer. This is how much you this coupon will cost to purchase..
        /// </summary>
        internal static string NullGiftValue {
            get {
                return ResourceManager.GetString("NullGiftValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a name for your offer..
        /// </summary>
        internal static string NullOfferName {
            get {
                return ResourceManager.GetString("NullOfferName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a limit per customer for your offer. This is how many coupons each individual customer is allowed to buy..
        /// </summary>
        internal static string NullPCCouponLimit {
            get {
                return ResourceManager.GetString("NullPCCouponLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to enter a retail value for your offer. This is how much your product or service typically costs..
        /// </summary>
        internal static string NullRetailValue {
            get {
                return ResourceManager.GetString("NullRetailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer name contains invalid characters. Please ensure it does not contain any of the following: &amp;lt;, &amp;gt;, {, }, or ;..
        /// </summary>
        internal static string OfferNameInvalidCharacters {
            get {
                return ResourceManager.GetString("OfferNameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but you already have an offer with that name. Offer names need to be unique. Please enter a different name..
        /// </summary>
        internal static string OfferNameTaken {
            get {
                return ResourceManager.GetString("OfferNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer name is too long. Offer names need to be less than 50 characters long..
        /// </summary>
        internal static string OfferNameTooLong {
            get {
                return ResourceManager.GetString("OfferNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer name is too short. Offer names need to be at least 5 characters long..
        /// </summary>
        internal static string OfferNameTooShort {
            get {
                return ResourceManager.GetString("OfferNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit of coupons per customer must be less than than or equal to the absolute limit of coupons to sell..
        /// </summary>
        internal static string PCCouponLimitGreaterThanAbsoluteLimit {
            get {
                return ResourceManager.GetString("PCCouponLimitGreaterThanAbsoluteLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon limit per customer needs to be greater than 0..
        /// </summary>
        internal static string PCCouponLimitLT0 {
            get {
                return ResourceManager.GetString("PCCouponLimitLT0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coupon limit per customer needs to be a number. For example, 2500..
        /// </summary>
        internal static string PCCouponLimitNAN {
            get {
                return ResourceManager.GetString("PCCouponLimitNAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your additional redeem details contains invalid characters. Please ensure it does not contain any of the following: &amp;lt;, &amp;gt;, {, }, or ;..
        /// </summary>
        internal static string RedeemDetailsInvalidCharacters {
            get {
                return ResourceManager.GetString("RedeemDetailsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your additional redeem details need to be less than 500 characters long..
        /// </summary>
        internal static string RedeemDetailsTooLong {
            get {
                return ResourceManager.GetString("RedeemDetailsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The retail value of your offer must be greater than than its gift value..
        /// </summary>
        internal static string RetailValueLessThanGiftValue {
            get {
                return ResourceManager.GetString("RetailValueLessThanGiftValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your retail value needs to be greater than $1.00..
        /// </summary>
        internal static string RetailValueLT1 {
            get {
                return ResourceManager.GetString("RetailValueLT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your retail value needs to be a number. For example, 25.00..
        /// </summary>
        internal static string RetailValueNAN {
            get {
                return ResourceManager.GetString("RetailValueNAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong with your form submission. Please try again..
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start date of your offer needs to be before its end date..
        /// </summary>
        internal static string StartDateLaterThanEndDate {
            get {
                return ResourceManager.GetString("StartDateLaterThanEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem uploading your image. Please try again..
        /// </summary>
        internal static string UploadError {
            get {
                return ResourceManager.GetString("UploadError", resourceCulture);
            }
        }
    }
}
