//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    
    public partial class Campaign_ListByNPO_Result1
    {
        public int CampaignID { get; set; }
        public string Name { get; set; }
        public int NPOID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CampaignDescription { get; set; }
        public Nullable<int> FundraisingGoal { get; set; }
        public string CampaignImage { get; set; }
        public Nullable<bool> ShowOnHome { get; set; }
        public Nullable<int> DisplayPriority { get; set; }
        public string CampaignGoal { get; set; }
        public bool HasAcceptedTerms { get; set; }
        public int CampaignStatusID { get; set; }
    }
}
