//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardType
    {
        public CardType()
        {
            this.PaymentOptions = new HashSet<PaymentOption>();
        }
    
        public int CardTypeID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PaymentOption> PaymentOptions { get; set; }
    }
}
