//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.MerchantLocations = new HashSet<MerchantLocation>();
            this.NPOes = new HashSet<NPO>();
            this.RedeemDetails = new HashSet<RedeemDetail>();
            this.cUsers = new HashSet<cUser>();
        }
    
        public string CityCode { get; set; }
        public Nullable<int> PoliticalDivisionID { get; set; }
        public string CountryCode { get; set; }
        public string Name { get; set; }
        public int CityID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual PoliticalDivision PoliticalDivision { get; set; }
        public virtual ICollection<MerchantLocation> MerchantLocations { get; set; }
        public virtual ICollection<NPO> NPOes { get; set; }
        public virtual ICollection<RedeemDetail> RedeemDetails { get; set; }
        public virtual ICollection<cUser> cUsers { get; set; }
    }
}
