//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cStatu
    {
        public cStatu()
        {
            this.cUsers = new HashSet<cUser>();
            this.NPOes = new HashSet<NPO>();
            this.Merchants = new HashSet<Merchant>();
            this.MerchantLocations = new HashSet<MerchantLocation>();
        }
    
        public int StatusID { get; set; }
        public string Name { get; set; }
        public string StatusDescription { get; set; }
    
        public virtual ICollection<cUser> cUsers { get; set; }
        public virtual ICollection<NPO> NPOes { get; set; }
        public virtual ICollection<Merchant> Merchants { get; set; }
        public virtual ICollection<MerchantLocation> MerchantLocations { get; set; }
    }
}
