//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cUser
    {
        public cUser()
        {
            this.PurchaseTransactions = new HashSet<PurchaseTransaction>();
            this.NPOes = new HashSet<NPO>();
            this.PaymentOptions = new HashSet<PaymentOption>();
            this.MerchantInfoes = new HashSet<MerchantInfo>();
            this.Merchants = new HashSet<Merchant>();
            this.Cities = new HashSet<City>();
        }
    
        public int cUserID { get; set; }
        public string Username { get; set; }
        public int StatusID { get; set; }
        public string StripeKey { get; set; }
    
        public virtual cStatu cStatu { get; set; }
        public virtual ICollection<PurchaseTransaction> PurchaseTransactions { get; set; }
        public virtual ICollection<NPO> NPOes { get; set; }
        public virtual ICollection<PaymentOption> PaymentOptions { get; set; }
        public virtual ICollection<MerchantInfo> MerchantInfoes { get; set; }
        public virtual ICollection<Merchant> Merchants { get; set; }
        public virtual ICollection<City> Cities { get; set; }
    }
}
