//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    
    public partial class Deal_Get_Result1
    {
        public int DealID { get; set; }
        public int MerchantID { get; set; }
        public string Name { get; set; }
        public string DealDescription { get; set; }
        public Nullable<int> AbsoluteCouponLimit { get; set; }
        public Nullable<int> LimitPerCustomer { get; set; }
        public string ImageURL { get; set; }
    }
}
