//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealSEO
    {
        public int DealSEOID { get; set; }
        public int DealID { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
    
        public virtual Deal Deal { get; set; }
    }
}
