//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealInstance
    {
        public DealInstance()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int DealInstanceID { get; set; }
        public int DealID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime RedeemableAfter { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int DealStatusID { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual DealStatu DealStatu { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
