//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public Deal()
        {
            this.DealInstances = new HashSet<DealInstance>();
            this.DealSEOs = new HashSet<DealSEO>();
            this.Prices = new HashSet<Price>();
            this.MerchantLocations = new HashSet<MerchantLocation>();
            this.RedeemDetails = new HashSet<RedeemDetail>();
            this.FinePrints = new HashSet<FinePrint>();
        }
    
        public int DealID { get; set; }
        public int MerchantID { get; set; }
        public string Name { get; set; }
        public string DealDescription { get; set; }
        public Nullable<int> AbsoluteCouponLimit { get; set; }
        public Nullable<int> LimitPerCustomer { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<DealInstance> DealInstances { get; set; }
        public virtual ICollection<DealSEO> DealSEOs { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
        public virtual ICollection<MerchantLocation> MerchantLocations { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual ICollection<RedeemDetail> RedeemDetails { get; set; }
        public virtual ICollection<FinePrint> FinePrints { get; set; }
    }
}
