//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealStatu
    {
        public DealStatu()
        {
            this.DealInstances = new HashSet<DealInstance>();
        }
    
        public int DealStatusID { get; set; }
        public string Name { get; set; }
        public string DealStatusDescription { get; set; }
    
        public virtual ICollection<DealInstance> DealInstances { get; set; }
    }
}
