//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinePrint
    {
        public FinePrint()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int FinePrintID { get; set; }
        public string Content { get; set; }
    
        public virtual ICollection<Deal> Deals { get; set; }
    }
}
