//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantSetting
    {
        public int MerchantSettingsID { get; set; }
        public int MerchantID { get; set; }
        public Nullable<bool> AutoAcceptRequests { get; set; }
    
        public virtual Merchant Merchant { get; set; }
    }
}
