//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantInfo
    {
        public int MerchantInfoID { get; set; }
        public int cUserID { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string MerchantDescription { get; set; }
    
        public virtual cUser cUser { get; set; }
    }
}
