//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MerchantLocation
    {
        public MerchantLocation()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int MerchantLocationID { get; set; }
        public int MerchantID { get; set; }
        public string cAddress { get; set; }
        public string PhoneNumber { get; set; }
        public int CityID { get; set; }
    
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual Merchant Merchant { get; set; }
        public virtual City City { get; set; }
    }
}
