//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Merchant
    {
        public Merchant()
        {
            this.Deals = new HashSet<Deal>();
            this.MerchantLocations = new HashSet<MerchantLocation>();
            this.MerchantStripeInfoes = new HashSet<MerchantStripeInfo>();
            this.NPOes = new HashSet<NPO>();
            this.NPOes1 = new HashSet<NPO>();
            this.MerchantSettings = new HashSet<MerchantSetting>();
        }
    
        public int MerchantID { get; set; }
        public string Name { get; set; }
        public string LargeLogo { get; set; }
        public string SmallLogo { get; set; }
        public string cAddress { get; set; }
        public string PostalCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public int StatusID { get; set; }
        public int cUserID { get; set; }
        public string Email { get; set; }
        public int CityID { get; set; }
    
        public virtual cStatu cStatu { get; set; }
        public virtual cUser cUser { get; set; }
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual ICollection<MerchantLocation> MerchantLocations { get; set; }
        public virtual ICollection<MerchantStripeInfo> MerchantStripeInfoes { get; set; }
        public virtual ICollection<NPO> NPOes { get; set; }
        public virtual ICollection<NPO> NPOes1 { get; set; }
        public virtual ICollection<MerchantSetting> MerchantSettings { get; set; }
    }
}
