//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.cUsers = new HashSet<cUser>();
        }
    
        public string Value { get; set; }
        public string NotificationCode { get; set; }
    
        public virtual ICollection<cUser> cUsers { get; set; }
    }
}
