//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPO
    {
        public NPO()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.NPOMailingLists = new HashSet<NPOMailingList>();
            this.Themes = new HashSet<Theme>();
            this.cUsers = new HashSet<cUser>();
            this.Merchants = new HashSet<Merchant>();
            this.Merchants1 = new HashSet<Merchant>();
            this.NPOSettings = new HashSet<NPOSetting>();
        }
    
        public int NPOID { get; set; }
        public string Name { get; set; }
        public string NPODescription { get; set; }
        public string cAddress { get; set; }
        public string PostalCode { get; set; }
        public string Website { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int StatusID { get; set; }
        public string Logo { get; set; }
        public string URL { get; set; }
        public bool UseAllMerchants { get; set; }
        public int CityID { get; set; }
    
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual cStatu cStatu { get; set; }
        public virtual ICollection<NPOMailingList> NPOMailingLists { get; set; }
        public virtual ICollection<Theme> Themes { get; set; }
        public virtual ICollection<cUser> cUsers { get; set; }
        public virtual ICollection<Merchant> Merchants { get; set; }
        public virtual ICollection<Merchant> Merchants1 { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<NPOSetting> NPOSettings { get; set; }
    }
}
