//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NPOSetting
    {
        public int NPOSettingID { get; set; }
        public int NPOID { get; set; }
        public bool AutoAcceptMerchantRequests { get; set; }
    
        public virtual NPO NPO { get; set; }
    }
}
