//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int PriceID { get; set; }
        public int DealID { get; set; }
        public decimal RetailValue { get; set; }
        public decimal GiftValue { get; set; }
        public decimal MerchantSplit { get; set; }
        public decimal NPOSplit { get; set; }
        public decimal OurSplit { get; set; }
    
        public virtual Deal Deal { get; set; }
    }
}
