//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseTransaction
    {
        public PurchaseTransaction()
        {
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
        }
    
        public int PurchaseTransactionID { get; set; }
        public int cUserID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
    
        public virtual cUser cUser { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
    }
}
