//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CouponsForGiving.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public int ThemeID { get; set; }
        public int NPOID { get; set; }
        public string Name { get; set; }
        public string ThemeDescription { get; set; }
        public string Content { get; set; }
        public bool Active { get; set; }
    
        public virtual NPO NPO { get; set; }
    }
}
